"""XLSX → markdown.

Each worksheet becomes an `## <sheet name>` section followed by a GitHub-
flavored markdown table. Empty trailing rows/columns are trimmed so sparse
sheets don't produce giant tables of blanks.

Formulas are rendered as their computed values when available (`data_only=True`
fallback). When openpyxl can't find cached values (e.g. a file that was
generated by a library and never opened in Excel), we fall back to the formula
string itself prefixed with `=` — better that the wiki see the formula than
a silent gap.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from openpyxl import load_workbook

_MAX_ROWS = 2000   # Guard against runaway sheets; bigger ones get truncated with a note.
_MAX_COLS = 64


def _stringify(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value.replace("|", "\\|").replace("\n", " ")
    return str(value)


def _trim_table(rows: list[list[Any]]) -> list[list[Any]]:
    # Drop trailing empty rows.
    while rows and all(cell in (None, "") for cell in rows[-1]):
        rows.pop()
    if not rows:
        return rows
    # Drop trailing empty columns.
    width = max(len(r) for r in rows)
    used = [False] * width
    for r in rows:
        for i, cell in enumerate(r):
            if cell not in (None, ""):
                used[i] = True
    last = max((i for i, u in enumerate(used) if u), default=-1)
    if last < 0:
        return []
    trimmed = [r[: last + 1] + [""] * max(0, last + 1 - len(r)) for r in rows]
    return trimmed


def _render_table(rows: list[list[Any]]) -> str:
    if not rows:
        return "_(sheet is empty)_\n"
    width = max(len(r) for r in rows)
    header = rows[0] + [""] * (width - len(rows[0]))
    body = rows[1:]
    # Promote header to "Column N" when the top row is blank.
    if all(h == "" for h in header):
        header = [f"Column {i + 1}" for i in range(width)]
        body = rows  # include what we thought was a blank header
    lines = ["| " + " | ".join(_stringify(c) for c in header) + " |",
             "| " + " | ".join(["---"] * width) + " |"]
    for r in body:
        padded = r + [""] * (width - len(r))
        lines.append("| " + " | ".join(_stringify(c) for c in padded) + " |")
    return "\n".join(lines) + "\n"


def convert_xlsx(path: Path) -> str:
    wb = load_workbook(path, data_only=True, read_only=True)
    sections: list[str] = []
    truncation_notes: list[str] = []
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        rows: list[list[Any]] = []
        truncated = False
        for row_idx, row in enumerate(
            ws.iter_rows(values_only=True, max_col=_MAX_COLS)
        ):
            if row_idx >= _MAX_ROWS:
                truncated = True
                break
            rows.append(list(row))
        rows = _trim_table(rows)
        sections.append(f"## {sheet_name}\n\n{_render_table(rows)}")
        if truncated:
            truncation_notes.append(sheet_name)
    wb.close()
    prefix = f"# {path.stem}\n\n"
    if truncation_notes:
        prefix += (
            f"> _Note: sheets truncated at {_MAX_ROWS} rows "
            f"or {_MAX_COLS} columns: {', '.join(truncation_notes)}_\n\n"
        )
    return prefix + "\n".join(sections)
